### ISSUE TITLE
Navigator: fontconfig package need update

### ISSUE THREAD

**Issue by shilkazx** [Anaconda-Platform/support#34]
On linux amd64 platform, when I execute anaconda-navigator, system issue the following error:

> python: symbol lookup error: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenType

After some google work, I found that update fontconfig(anaconda package version is 2.11.1, I use 2.11.95 instead) would solve the problem.  The solution is proposed from archlinux forum, 
[https://bugs.archlinux.org/task/48827](url)

**Comment by stephenakearns** [comment]
Hi @goanpeca - can you comment on this issue?

**Comment by goanpeca** [comment]
Nop, not familiar with that problem.

**Comment by stephenakearns** [comment]
@goanpeca - can you suggest a severity for this issue?

**Comment by stephenakearns** [comment]
@ccordoba12 - can I get your thoughts on this issue?

**Comment by ccordoba12** [comment]
This problem happens in Fedora 22+ and Arch Linux. It's caused because those distros are using a more recent version of fontconfig (2.12.0) than the one we have in our official channels (2.11.1).

Since we don't provide our own conda package for pango, Qt (specifically, its Gtk style theme, I think) tries to use the system pango. This is compiled against the newer fontconfig version but it looks for ours because Qt was linked against it. And this causes the error reported by @shilkazx, given that the two fontconfig versions have a different API.

There are two possible solutions to this problem:

1. Make our Qt package to depend on our Pango one. This is the easiest solution because it only requires adding this new dependency to the Qt recipe, and releasing new Qt packages for Linux.
2. Update our fontconfig package to 2.12.0. This is harder because we need to recompile all packages that depend on it, and also agree with the conda-forge team to do the same. Besides, this change not only affects Linux but also OS X.

I'm pinging @msarahan to see what he thinks about this.

**Comment by msarahan** [comment]
I don't really care which way.  Either is fine.  1 sounds like less work.

**Comment by shilkazx** [comment]
The easy but tricky way to solve this problem is suggest Fedora and Arch user remove anaconda's fontconfig package. @ccordoba12

**Comment by ccordoba12** [comment]
@shilkazx, I don't know how well that would work. But I think it's easier to just demand pango as a dependency of Qt, something that will work regardless of the user preferred distro :-)

**Comment by shilkazx** [comment]
@ccordoba12 Wow, that's great!! I recall another bug bothering me for a long while is that anaconda's curl package is not compatible with a widely used package management software named "yaourt" in Archlinux distro. And I use the same way to resolve the problem. In my humble opinion, remove some package replicated but incompatible with system might be a easy and general methodology for many quirky problem. ^_^

**Comment by csoja** [comment]
Our fontconfig package was updated to v2.12.1 on December 11th.  There has also been quite a bit of work done on Qt since this issue was opened.  I am closing this as I believe it should be fixed at this point.  If there is still a problem, please let us know.
