### ISSUE TITLE
Build: can't find meta.yaml file

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Platform/support#8]
Request for help on google forum - posted by malingreal@gmail.com 

https://groups.google.com/a/continuum.io/forum/#!msg/anaconda/GwHh68igyCk/koIVo76YCgAJ
1. No yum support due to the root limitation.
2. Sometime can't find the meta.yaml file, although the local conda build workflow works like a charm.

**Comment by srossross** [comment]
@stephenakearns I'm moving this to the icebox. Not sure what the action item for this is. No way to reproduce.

**Comment by stephenakearns** [comment]
@csoja - can you review the google thread - is the issue related to Conda Build

**Comment by csoja** [comment]
@stephenakearns <https://github.com/stephenakearns> - sounds like the user
is able to use conda build - but having issues with the anaconda-build
system.  I think we need more information in order to actually do anything
on this one.  What is he doing when the yaml file cannot be found? Why does
the user need yum?

On Fri, Jan 22, 2016 at 2:50 PM, Stephen Kearns <notifications@github.com>
wrote:

> @csoja <https://github.com/csoja> - can you review the google thread - is
> the issue related to Conda Build
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaconda-Server/support/issues/8#issuecomment-174042603>
> .
>



-- 
*Crystal Soja*
*Anaconda Distribution Product Manager*

**Comment by koverholt** [comment]
Closing as stale. And the Anaconda.org cloud builders have been deprecated (https://www.anaconda.com/blog/developer-blog/powering-down-the-anaconda-build-ci-system/).
